name: Build Tauri App iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-latest
    env:
      CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
      CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      PROVISION_PROFILE_BASE64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Node.js setup
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Rust setup (Tauri dùng Rust)
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Cài dependencies
      - run: npm install

      # Giải mã certificate & provisioning profile
      - run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > ios_cert.p12
          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > profile.mobileprovision

      # Build iOS
      - run: npm run tauri ios -- --signing-cert ios_cert.p12 --provisioning-profile profile.mobileprovision

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: tauri-ios
          path: src-tauri/target/release/bundle/ios/
